  shadowtraffic_setup:
    image: shadowtraffic/shadowtraffic:latest
    hostname: shadowtraffic_setup
    profiles: [ prepopulate ]
    depends_on:
      schema-registry:
        condition: service_healthy
    volumes:
      - type: bind
        source: "./shadowtraffic"
        target: /etc/shadowtraffic
        read_only: true
    env_file: "shadowtraffic_license.env"
    command: --config /etc/shadowtraffic/setup.json --seed 1234
    restart: no
