  shadowtraffic_background_evolved:
    image: shadowtraffic/shadowtraffic:latest
    hostname: shadowtraffic_run
    profiles: [ background ]
    depends_on:
      schema-registry:
        condition: service_healthy
    volumes:
      - type: bind
        source: "./shadowtraffic"
        target: /etc/shadowtraffic
        read_only: true
    env_file: "shadowtraffic_license.env"
    command: --config /etc/shadowtraffic/background-evolved.json --seed 1234
    restart: on-failure
