
  spark-iceberg:
    #image: local/spark-iceberg:latest
    image: streambased/spark-iceberg:latest
    hostname: spark
    container_name: spark-iceberg
    platform: linux/amd64
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=sbpk_12345678
      - AWS_SECRET_ACCESS_KEY=sbsk_12345678
      - DIRECTSTREAM_CATALOG_URI=http:\/\/directstream:11001
      - DIRECTSTREAM_S3_ENDPOINT=http:\/\/directstream:11000
      - SPARK_MASTER_HOST=spark-iceberg
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8180
    ports:
      - 8888:8888
      - 10000:10000
      - 10001:10001
      - 4040-4050:4040-4050
      - 15002:15002
      - 8180:8180

  rest:
    image: apache/iceberg-rest-fixture:1.8.1
    container_name: iceberg-rest
    ports:
      - 8181:8181
    environment:
      - CATALOG_CATALOG__IMPL=org.apache.iceberg.jdbc.JdbcCatalog
      - CATALOG_URI=jdbc:sqlite:file:/tmp/iceberg.db
      - CATALOG_JDBC_USER=user
      - CATALOG_JDBC_PASSWORD=password
      - REST_PORT=8181
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000

  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    networks:
      default:
        aliases:
          - warehouse.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      /usr/bin/mc rm -r --force minio/coldset;
      /usr/bin/mc mb minio/coldset;
      /usr/bin/mc policy set public minio/coldset;
      tail -f /dev/null
      "
